### ISSUE TITLE
Anteproyecto

### ISSUE THREAD

**Issue by ndirenzo** [fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-Pochoclera#1]
Subimos el anteproyecto en la pestaña "doc". Saludos!

**Comment by rarias** [comment]
* Carátula no oficial (cambiar x la oficial - ver campus)
     Editar también el READ.ME de la carpeta Code donde figure:
         Nombre del proyecto
         Integrantes del grupo de trabajo
* Diagama en bloques, falta la alimentación del sistema (220VAC + fuente)
Podemos trabajar un poco sobre ese diagrama en bloques (lo discutimos en clase)
